<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gossip.proto

namespace Phluxor\Cluster\Metadata\ProtoBuf;

class Gossip
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Any::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\x85\x06\x0A\x0Cgossip.proto\x12\x07cluster\"L\x0A\x0DGossipRequest\x12\x16\x0A\x0Efrom_member_id\x18\x02 \x01(\x09\x12#\x0A\x05state\x18\x01 \x01(\x0B2\x14.cluster.GossipState\"5\x0A\x0EGossipResponse\x12#\x0A\x05state\x18\x01 \x01(\x0B2\x14.cluster.GossipState\"\x8D\x01\x0A\x0BGossipState\x122\x0A\x07members\x18\x01 \x03(\x0B2!.cluster.GossipState.MembersEntry\x1AJ\x0A\x0CMembersEntry\x12\x0B\x0A\x03key\x18\x01 \x01(\x09\x12)\x0A\x05value\x18\x02 \x01(\x0B2\x1A.cluster.GossipMemberState:\x028\x01\"\x93\x01\x0A\x11GossipMemberState\x126\x0A\x06values\x18\x01 \x03(\x0B2&.cluster.GossipMemberState.ValuesEntry\x1AF\x0A\x0BValuesEntry\x12\x0B\x0A\x03key\x18\x01 \x01(\x09\x12&\x0A\x05value\x18\x02 \x01(\x0B2\x17.cluster.GossipKeyValue:\x028\x01\"y\x0A\x0EGossipKeyValue\x12\x17\x0A\x0Fsequence_number\x18\x02 \x01(\x03\x12#\x0A\x05value\x18\x04 \x01(\x0B2\x14.google.protobuf.Any\x12)\x0A!local_timestamp_unix_milliseconds\x18\x05 \x01(\x03\"}\x0A\x09GossipMap\x12,\x0A\x05items\x18\x01 \x03(\x0B2\x1D.cluster.GossipMap.ItemsEntry\x1AB\x0A\x0AItemsEntry\x12\x0B\x0A\x03key\x18\x01 \x01(\x09\x12#\x0A\x05value\x18\x02 \x01(\x0B2\x14.google.protobuf.Any:\x028\x01B?\xCA\x02\x18Phluxor\\Cluster\\ProtoBuf\xE2\x02!Phluxor\\Cluster\\Metadata\\ProtoBufb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

