<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grain.proto

namespace Phluxor\Cluster\Metadata\ProtoBuf;

class Grain
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\x9E\x03\x0A\x0Bgrain.proto\x12\x07cluster\"U\x0A\x0CGrainRequest\x12\x14\x0A\x0Cmethod_index\x18\x01 \x01(\x05\x12\x14\x0A\x0Cmessage_data\x18\x02 \x01(\x0C\x12\x19\x0A\x11message_type_name\x18\x03 \x01(\x09\"@\x0A\x0DGrainResponse\x12\x14\x0A\x0Cmessage_data\x18\x01 \x01(\x0C\x12\x19\x0A\x11message_type_name\x18\x02 \x01(\x09\"\xA3\x01\x0A\x12GrainErrorResponse\x12\x0E\x0A\x06reason\x18\x01 \x01(\x09\x12\x0F\x0A\x07message\x18\x02 \x01(\x09\x12;\x0A\x08metadata\x18\x03 \x03(\x0B2).cluster.GrainErrorResponse.MetadataEntry\x1A/\x0A\x0DMetadataEntry\x12\x0B\x0A\x03key\x18\x01 \x01(\x09\x12\x0D\x0A\x05value\x18\x02 \x01(\x09:\x028\x01B?\xCA\x02\x18Phluxor\\Cluster\\ProtoBuf\xE2\x02!Phluxor\\Cluster\\Metadata\\ProtoBufb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

