<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cluster.proto

namespace Phluxor\Cluster\ProtoBuf\PackedActivations;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cluster.PackedActivations.Kind</code>
 */
class Kind extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>repeated .cluster.PackedActivations.Activation activations = 2;</code>
     */
    private $activations;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type array<\Phluxor\Cluster\ProtoBuf\PackedActivations\Activation>|\Google\Protobuf\Internal\RepeatedField $activations
     * }
     */
    public function __construct($data = NULL) {
        \Phluxor\Cluster\Metadata\ProtoBuf\Cluster::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .cluster.PackedActivations.Activation activations = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getActivations()
    {
        return $this->activations;
    }

    /**
     * Generated from protobuf field <code>repeated .cluster.PackedActivations.Activation activations = 2;</code>
     * @param array<\Phluxor\Cluster\ProtoBuf\PackedActivations\Activation>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setActivations($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Phluxor\Cluster\ProtoBuf\PackedActivations\Activation::class);
        $this->activations = $arr;

        return $this;
    }

}

