<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cluster.proto

namespace Phluxor\Cluster\ProtoBuf\IdentityHandoverRequest;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cluster.IdentityHandoverRequest.Topology</code>
 */
class Topology extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 topology_hash = 1;</code>
     */
    protected $topology_hash = 0;
    /**
     * Generated from protobuf field <code>repeated .cluster.Member members = 3;</code>
     */
    private $members;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $topology_hash
     *     @type array<\Phluxor\Cluster\ProtoBuf\Member>|\Google\Protobuf\Internal\RepeatedField $members
     * }
     */
    public function __construct($data = NULL) {
        \Phluxor\Cluster\Metadata\ProtoBuf\Cluster::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 topology_hash = 1;</code>
     * @return int|string
     */
    public function getTopologyHash()
    {
        return $this->topology_hash;
    }

    /**
     * Generated from protobuf field <code>uint64 topology_hash = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTopologyHash($var)
    {
        GPBUtil::checkUint64($var);
        $this->topology_hash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .cluster.Member members = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMembers()
    {
        return $this->members;
    }

    /**
     * Generated from protobuf field <code>repeated .cluster.Member members = 3;</code>
     * @param array<\Phluxor\Cluster\ProtoBuf\Member>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMembers($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Phluxor\Cluster\ProtoBuf\Member::class);
        $this->members = $arr;

        return $this;
    }

}

