<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: actor.proto

namespace Phluxor\Metadata\ProtoBuf;

class Actor
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xE7\x03\x0A\x0Bactor.proto\x12\x05actor\"6\x0A\x03PID\x12\x0F\x0A\x07address\x18\x01 \x01(\x09\x12\x0A\x0A\x02id\x18\x02 \x01(\x09\x12\x12\x0A\x0Arequest_id\x18\x03 \x01(\x0D\"\x0C\x0A\x0APoisonPill\"0\x0A\x12DeadLetterResponse\x12\x1A\x0A\x06target\x18\x01 \x01(\x0B2\x0A.actor.PID\"\$\x0A\x05Watch\x12\x1B\x0A\x07watcher\x18\x01 \x01(\x0B2\x0A.actor.PID\"&\x0A\x07Unwatch\x12\x1B\x0A\x07watcher\x18\x01 \x01(\x0B2\x0A.actor.PID\"K\x0A\x0ATerminated\x12\x17\x0A\x03who\x18\x01 \x01(\x0B2\x0A.actor.PID\x12\$\x0A\x03why\x18\x02 \x01(\x0E2\x17.actor.TerminatedReason\"\x06\x0A\x04Stop\"\x07\x0A\x05Touch\"\"\x0A\x07Touched\x12\x17\x0A\x03who\x18\x01 \x01(\x0B2\x0A.actor.PID*D\x0A\x10TerminatedReason\x12\x0B\x0A\x07Stopped\x10\x00\x12\x15\x0A\x11AddressTerminated\x10\x01\x12\x0C\x0A\x08NotFound\x10\x02B;\xCA\x02\x1CPhluxor\\ActorSystem\\ProtoBuf\xE2\x02\x19Phluxor\\Metadata\\ProtoBufb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

