<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cluster.proto

namespace Phluxor\Cluster\ProtoBuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cluster.Activation</code>
 */
class Activation extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.actor.Pid pid = 1;</code>
     */
    protected $pid = null;
    /**
     * Generated from protobuf field <code>.cluster.ClusterIdentity cluster_identity = 2;</code>
     */
    protected $cluster_identity = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Phluxor\ActorSystem\ProtoBuf\Pid $pid
     *     @type \Phluxor\Cluster\ProtoBuf\ClusterIdentity $cluster_identity
     * }
     */
    public function __construct($data = NULL) {
        \Phluxor\Cluster\Metadata\ProtoBuf\Cluster::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.actor.Pid pid = 1;</code>
     * @return \Phluxor\ActorSystem\ProtoBuf\Pid|null
     */
    public function getPid()
    {
        return $this->pid;
    }

    public function hasPid()
    {
        return isset($this->pid);
    }

    public function clearPid()
    {
        unset($this->pid);
    }

    /**
     * Generated from protobuf field <code>.actor.Pid pid = 1;</code>
     * @param \Phluxor\ActorSystem\ProtoBuf\Pid $var
     * @return $this
     */
    public function setPid($var)
    {
        GPBUtil::checkMessage($var, \Phluxor\ActorSystem\ProtoBuf\Pid::class);
        $this->pid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.cluster.ClusterIdentity cluster_identity = 2;</code>
     * @return \Phluxor\Cluster\ProtoBuf\ClusterIdentity|null
     */
    public function getClusterIdentity()
    {
        return $this->cluster_identity;
    }

    public function hasClusterIdentity()
    {
        return isset($this->cluster_identity);
    }

    public function clearClusterIdentity()
    {
        unset($this->cluster_identity);
    }

    /**
     * Generated from protobuf field <code>.cluster.ClusterIdentity cluster_identity = 2;</code>
     * @param \Phluxor\Cluster\ProtoBuf\ClusterIdentity $var
     * @return $this
     */
    public function setClusterIdentity($var)
    {
        GPBUtil::checkMessage($var, \Phluxor\Cluster\ProtoBuf\ClusterIdentity::class);
        $this->cluster_identity = $var;

        return $this;
    }

}

