<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cluster.proto

namespace Phluxor\Cluster\ProtoBuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cluster.ActivationRequest</code>
 */
class ActivationRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.cluster.ClusterIdentity cluster_identity = 1;</code>
     */
    protected $cluster_identity = null;
    /**
     * Generated from protobuf field <code>string request_id = 2;</code>
     */
    protected $request_id = '';
    /**
     * Generated from protobuf field <code>uint64 topology_hash = 3;</code>
     */
    protected $topology_hash = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Phluxor\Cluster\ProtoBuf\ClusterIdentity $cluster_identity
     *     @type string $request_id
     *     @type int|string $topology_hash
     * }
     */
    public function __construct($data = NULL) {
        \Phluxor\Cluster\Metadata\ProtoBuf\Cluster::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.cluster.ClusterIdentity cluster_identity = 1;</code>
     * @return \Phluxor\Cluster\ProtoBuf\ClusterIdentity|null
     */
    public function getClusterIdentity()
    {
        return $this->cluster_identity;
    }

    public function hasClusterIdentity()
    {
        return isset($this->cluster_identity);
    }

    public function clearClusterIdentity()
    {
        unset($this->cluster_identity);
    }

    /**
     * Generated from protobuf field <code>.cluster.ClusterIdentity cluster_identity = 1;</code>
     * @param \Phluxor\Cluster\ProtoBuf\ClusterIdentity $var
     * @return $this
     */
    public function setClusterIdentity($var)
    {
        GPBUtil::checkMessage($var, \Phluxor\Cluster\ProtoBuf\ClusterIdentity::class);
        $this->cluster_identity = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string request_id = 2;</code>
     * @return string
     */
    public function getRequestId()
    {
        return $this->request_id;
    }

    /**
     * Generated from protobuf field <code>string request_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRequestId($var)
    {
        GPBUtil::checkString($var, True);
        $this->request_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 topology_hash = 3;</code>
     * @return int|string
     */
    public function getTopologyHash()
    {
        return $this->topology_hash;
    }

    /**
     * Generated from protobuf field <code>uint64 topology_hash = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTopologyHash($var)
    {
        GPBUtil::checkUint64($var);
        $this->topology_hash = $var;

        return $this;
    }

}

