<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cluster.proto

namespace Phluxor\Cluster\ProtoBuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cluster.ActivationResponse</code>
 */
class ActivationResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.actor.Pid pid = 1;</code>
     */
    protected $pid = null;
    /**
     * Generated from protobuf field <code>bool failed = 2;</code>
     */
    protected $failed = false;
    /**
     * Generated from protobuf field <code>uint64 topology_hash = 3;</code>
     */
    protected $topology_hash = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Phluxor\ActorSystem\ProtoBuf\Pid $pid
     *     @type bool $failed
     *     @type int|string $topology_hash
     * }
     */
    public function __construct($data = NULL) {
        \Phluxor\Cluster\Metadata\ProtoBuf\Cluster::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.actor.Pid pid = 1;</code>
     * @return \Phluxor\ActorSystem\ProtoBuf\Pid|null
     */
    public function getPid()
    {
        return $this->pid;
    }

    public function hasPid()
    {
        return isset($this->pid);
    }

    public function clearPid()
    {
        unset($this->pid);
    }

    /**
     * Generated from protobuf field <code>.actor.Pid pid = 1;</code>
     * @param \Phluxor\ActorSystem\ProtoBuf\Pid $var
     * @return $this
     */
    public function setPid($var)
    {
        GPBUtil::checkMessage($var, \Phluxor\ActorSystem\ProtoBuf\Pid::class);
        $this->pid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool failed = 2;</code>
     * @return bool
     */
    public function getFailed()
    {
        return $this->failed;
    }

    /**
     * Generated from protobuf field <code>bool failed = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setFailed($var)
    {
        GPBUtil::checkBool($var);
        $this->failed = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 topology_hash = 3;</code>
     * @return int|string
     */
    public function getTopologyHash()
    {
        return $this->topology_hash;
    }

    /**
     * Generated from protobuf field <code>uint64 topology_hash = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTopologyHash($var)
    {
        GPBUtil::checkUint64($var);
        $this->topology_hash = $var;

        return $this;
    }

}

