<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cluster.proto

namespace Phluxor\Cluster\ProtoBuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cluster.ActorStatistics</code>
 */
class ActorStatistics extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>map<string, int64> actor_count = 1;</code>
     */
    private $actor_count;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array|\Google\Protobuf\Internal\MapField $actor_count
     * }
     */
    public function __construct($data = NULL) {
        \Phluxor\Cluster\Metadata\ProtoBuf\Cluster::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>map<string, int64> actor_count = 1;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getActorCount()
    {
        return $this->actor_count;
    }

    /**
     * Generated from protobuf field <code>map<string, int64> actor_count = 1;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setActorCount($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::INT64);
        $this->actor_count = $arr;

        return $this;
    }

}

