<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cluster.proto

namespace Phluxor\Cluster\ProtoBuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cluster.ClusterTopologyNotification</code>
 */
class ClusterTopologyNotification extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string member_id = 1;</code>
     */
    protected $member_id = '';
    /**
     * Generated from protobuf field <code>uint32 topology_hash = 2;</code>
     */
    protected $topology_hash = 0;
    /**
     * Generated from protobuf field <code>string leader_id = 3;</code>
     */
    protected $leader_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $member_id
     *     @type int $topology_hash
     *     @type string $leader_id
     * }
     */
    public function __construct($data = NULL) {
        \Phluxor\Cluster\Metadata\ProtoBuf\Cluster::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string member_id = 1;</code>
     * @return string
     */
    public function getMemberId()
    {
        return $this->member_id;
    }

    /**
     * Generated from protobuf field <code>string member_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMemberId($var)
    {
        GPBUtil::checkString($var, True);
        $this->member_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 topology_hash = 2;</code>
     * @return int
     */
    public function getTopologyHash()
    {
        return $this->topology_hash;
    }

    /**
     * Generated from protobuf field <code>uint32 topology_hash = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setTopologyHash($var)
    {
        GPBUtil::checkUint32($var);
        $this->topology_hash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string leader_id = 3;</code>
     * @return string
     */
    public function getLeaderId()
    {
        return $this->leader_id;
    }

    /**
     * Generated from protobuf field <code>string leader_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setLeaderId($var)
    {
        GPBUtil::checkString($var, True);
        $this->leader_id = $var;

        return $this;
    }

}

