<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cluster.proto

namespace Phluxor\Cluster\ProtoBuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cluster.ClusterTopology</code>
 */
class ClusterTopology extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 topology_hash = 1;</code>
     */
    protected $topology_hash = 0;
    /**
     * Generated from protobuf field <code>repeated .cluster.Member members = 2;</code>
     */
    private $members;
    /**
     * Generated from protobuf field <code>repeated .cluster.Member joined = 3;</code>
     */
    private $joined;
    /**
     * Generated from protobuf field <code>repeated .cluster.Member left = 4;</code>
     */
    private $left;
    /**
     * Generated from protobuf field <code>repeated string blocked = 5;</code>
     */
    private $blocked;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $topology_hash
     *     @type array<\Phluxor\Cluster\ProtoBuf\Member>|\Google\Protobuf\Internal\RepeatedField $members
     *     @type array<\Phluxor\Cluster\ProtoBuf\Member>|\Google\Protobuf\Internal\RepeatedField $joined
     *     @type array<\Phluxor\Cluster\ProtoBuf\Member>|\Google\Protobuf\Internal\RepeatedField $left
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $blocked
     * }
     */
    public function __construct($data = NULL) {
        \Phluxor\Cluster\Metadata\ProtoBuf\Cluster::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 topology_hash = 1;</code>
     * @return int|string
     */
    public function getTopologyHash()
    {
        return $this->topology_hash;
    }

    /**
     * Generated from protobuf field <code>uint64 topology_hash = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTopologyHash($var)
    {
        GPBUtil::checkUint64($var);
        $this->topology_hash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .cluster.Member members = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMembers()
    {
        return $this->members;
    }

    /**
     * Generated from protobuf field <code>repeated .cluster.Member members = 2;</code>
     * @param array<\Phluxor\Cluster\ProtoBuf\Member>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMembers($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Phluxor\Cluster\ProtoBuf\Member::class);
        $this->members = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .cluster.Member joined = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getJoined()
    {
        return $this->joined;
    }

    /**
     * Generated from protobuf field <code>repeated .cluster.Member joined = 3;</code>
     * @param array<\Phluxor\Cluster\ProtoBuf\Member>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setJoined($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Phluxor\Cluster\ProtoBuf\Member::class);
        $this->joined = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .cluster.Member left = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLeft()
    {
        return $this->left;
    }

    /**
     * Generated from protobuf field <code>repeated .cluster.Member left = 4;</code>
     * @param array<\Phluxor\Cluster\ProtoBuf\Member>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLeft($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Phluxor\Cluster\ProtoBuf\Member::class);
        $this->left = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string blocked = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getBlocked()
    {
        return $this->blocked;
    }

    /**
     * Generated from protobuf field <code>repeated string blocked = 5;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setBlocked($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->blocked = $arr;

        return $this;
    }

}

