<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grain.proto

namespace Phluxor\Cluster\ProtoBuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cluster.GrainResponse</code>
 */
class GrainResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes message_data = 1;</code>
     */
    protected $message_data = '';
    /**
     * Generated from protobuf field <code>string message_type_name = 2;</code>
     */
    protected $message_type_name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $message_data
     *     @type string $message_type_name
     * }
     */
    public function __construct($data = NULL) {
        \Phluxor\Cluster\Metadata\ProtoBuf\Grain::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes message_data = 1;</code>
     * @return string
     */
    public function getMessageData()
    {
        return $this->message_data;
    }

    /**
     * Generated from protobuf field <code>bytes message_data = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMessageData($var)
    {
        GPBUtil::checkString($var, False);
        $this->message_data = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string message_type_name = 2;</code>
     * @return string
     */
    public function getMessageTypeName()
    {
        return $this->message_type_name;
    }

    /**
     * Generated from protobuf field <code>string message_type_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMessageTypeName($var)
    {
        GPBUtil::checkString($var, True);
        $this->message_type_name = $var;

        return $this;
    }

}

