<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cluster.proto

namespace Phluxor\Cluster\ProtoBuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cluster.MemberHeartbeat</code>
 */
class MemberHeartbeat extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.cluster.ActorStatistics actor_statistics = 1;</code>
     */
    protected $actor_statistics = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Phluxor\Cluster\ProtoBuf\ActorStatistics $actor_statistics
     * }
     */
    public function __construct($data = NULL) {
        \Phluxor\Cluster\Metadata\ProtoBuf\Cluster::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.cluster.ActorStatistics actor_statistics = 1;</code>
     * @return \Phluxor\Cluster\ProtoBuf\ActorStatistics|null
     */
    public function getActorStatistics()
    {
        return $this->actor_statistics;
    }

    public function hasActorStatistics()
    {
        return isset($this->actor_statistics);
    }

    public function clearActorStatistics()
    {
        unset($this->actor_statistics);
    }

    /**
     * Generated from protobuf field <code>.cluster.ActorStatistics actor_statistics = 1;</code>
     * @param \Phluxor\Cluster\ProtoBuf\ActorStatistics $var
     * @return $this
     */
    public function setActorStatistics($var)
    {
        GPBUtil::checkMessage($var, \Phluxor\Cluster\ProtoBuf\ActorStatistics::class);
        $this->actor_statistics = $var;

        return $this;
    }

}

