<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cluster.proto

namespace Phluxor\Cluster\ProtoBuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cluster.PackedActivations</code>
 */
class PackedActivations extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string address = 1;</code>
     */
    protected $address = '';
    /**
     * Generated from protobuf field <code>repeated .cluster.PackedActivations.Kind actors = 2;</code>
     */
    private $actors;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $address
     *     @type array<\Phluxor\Cluster\ProtoBuf\PackedActivations\Kind>|\Google\Protobuf\Internal\RepeatedField $actors
     * }
     */
    public function __construct($data = NULL) {
        \Phluxor\Cluster\Metadata\ProtoBuf\Cluster::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string address = 1;</code>
     * @return string
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * Generated from protobuf field <code>string address = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .cluster.PackedActivations.Kind actors = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getActors()
    {
        return $this->actors;
    }

    /**
     * Generated from protobuf field <code>repeated .cluster.PackedActivations.Kind actors = 2;</code>
     * @param array<\Phluxor\Cluster\ProtoBuf\PackedActivations\Kind>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setActors($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Phluxor\Cluster\ProtoBuf\PackedActivations\Kind::class);
        $this->actors = $arr;

        return $this;
    }

}

