<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pubsub.proto

namespace Phluxor\Cluster\ProtoBuf;

use UnexpectedValueException;

/**
 * Status of the whole published batch or single message
 *
 * Protobuf type <code>cluster.PublishStatus</code>
 */
class PublishStatus
{
    /**
     * Batch or message was successfully published according to the delivery guarantees
     *
     * Generated from protobuf enum <code>Ok = 0;</code>
     */
    const Ok = 0;
    /**
     * Topic failed to forward the message
     *
     * Generated from protobuf enum <code>Failed = 1;</code>
     */
    const Failed = 1;

    private static $valueToName = [
        self::Ok => 'Ok',
        self::Failed => 'Failed',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

