<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pubsub.proto

namespace Phluxor\Cluster\ProtoBuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Contains message byte representation and type reference
 *
 * Generated from protobuf message <code>cluster.PubSubEnvelope</code>
 */
class PubSubEnvelope extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 type_id = 1;</code>
     */
    protected $type_id = 0;
    /**
     * Generated from protobuf field <code>bytes message_data = 2;</code>
     */
    protected $message_data = '';
    /**
     * Generated from protobuf field <code>int32 serializer_id = 3;</code>
     */
    protected $serializer_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $type_id
     *     @type string $message_data
     *     @type int $serializer_id
     * }
     */
    public function __construct($data = NULL) {
        \Phluxor\Cluster\Metadata\ProtoBuf\Pubsub::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 type_id = 1;</code>
     * @return int
     */
    public function getTypeId()
    {
        return $this->type_id;
    }

    /**
     * Generated from protobuf field <code>int32 type_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setTypeId($var)
    {
        GPBUtil::checkInt32($var);
        $this->type_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes message_data = 2;</code>
     * @return string
     */
    public function getMessageData()
    {
        return $this->message_data;
    }

    /**
     * Generated from protobuf field <code>bytes message_data = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMessageData($var)
    {
        GPBUtil::checkString($var, False);
        $this->message_data = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 serializer_id = 3;</code>
     * @return int
     */
    public function getSerializerId()
    {
        return $this->serializer_id;
    }

    /**
     * Generated from protobuf field <code>int32 serializer_id = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setSerializerId($var)
    {
        GPBUtil::checkInt32($var);
        $this->serializer_id = $var;

        return $this;
    }

}

