<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pubsub.proto

namespace Phluxor\Cluster\ProtoBuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Message sent from publisher to topic actor
 * See also PubSubBatch
 *
 * Generated from protobuf message <code>cluster.PubSubBatchTransport</code>
 */
class PubSubBatchTransport extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string type_names = 1;</code>
     */
    private $type_names;
    /**
     * Generated from protobuf field <code>repeated .cluster.PubSubEnvelope envelopes = 2;</code>
     */
    private $envelopes;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $type_names
     *     @type array<\Phluxor\Cluster\ProtoBuf\PubSubEnvelope>|\Google\Protobuf\Internal\RepeatedField $envelopes
     * }
     */
    public function __construct($data = NULL) {
        \Phluxor\Cluster\Metadata\ProtoBuf\Pubsub::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated string type_names = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTypeNames()
    {
        return $this->type_names;
    }

    /**
     * Generated from protobuf field <code>repeated string type_names = 1;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTypeNames($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->type_names = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .cluster.PubSubEnvelope envelopes = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getEnvelopes()
    {
        return $this->envelopes;
    }

    /**
     * Generated from protobuf field <code>repeated .cluster.PubSubEnvelope envelopes = 2;</code>
     * @param array<\Phluxor\Cluster\ProtoBuf\PubSubEnvelope>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setEnvelopes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Phluxor\Cluster\ProtoBuf\PubSubEnvelope::class);
        $this->envelopes = $arr;

        return $this;
    }

}

