<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pubsub.proto

namespace Phluxor\Cluster\ProtoBuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Identifies a subscriber by either ClusterIdentity or PID
 *
 * Generated from protobuf message <code>cluster.SubscriberIdentity</code>
 */
class SubscriberIdentity extends \Google\Protobuf\Internal\Message
{
    protected $Identity;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Phluxor\ActorSystem\ProtoBuf\Pid $pid
     *     @type \Phluxor\Cluster\ProtoBuf\ClusterIdentity $cluster_identity
     * }
     */
    public function __construct($data = NULL) {
        \Phluxor\Cluster\Metadata\ProtoBuf\Pubsub::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.actor.Pid pid = 1;</code>
     * @return \Phluxor\ActorSystem\ProtoBuf\Pid|null
     */
    public function getPid()
    {
        return $this->readOneof(1);
    }

    public function hasPid()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.actor.Pid pid = 1;</code>
     * @param \Phluxor\ActorSystem\ProtoBuf\Pid $var
     * @return $this
     */
    public function setPid($var)
    {
        GPBUtil::checkMessage($var, \Phluxor\ActorSystem\ProtoBuf\Pid::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.cluster.ClusterIdentity cluster_identity = 2;</code>
     * @return \Phluxor\Cluster\ProtoBuf\ClusterIdentity|null
     */
    public function getClusterIdentity()
    {
        return $this->readOneof(2);
    }

    public function hasClusterIdentity()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.cluster.ClusterIdentity cluster_identity = 2;</code>
     * @param \Phluxor\Cluster\ProtoBuf\ClusterIdentity $var
     * @return $this
     */
    public function setClusterIdentity($var)
    {
        GPBUtil::checkMessage($var, \Phluxor\Cluster\ProtoBuf\ClusterIdentity::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getIdentity()
    {
        return $this->whichOneof("Identity");
    }

}

