<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pubsub.proto

namespace Phluxor\Cluster\ProtoBuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Contains information about a failed delivery
 *
 * Generated from protobuf message <code>cluster.SubscriberDeliveryReport</code>
 */
class SubscriberDeliveryReport extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.cluster.SubscriberIdentity subscriber = 1;</code>
     */
    protected $subscriber = null;
    /**
     * Generated from protobuf field <code>.cluster.DeliveryStatus status = 2;</code>
     */
    protected $status = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Phluxor\Cluster\ProtoBuf\SubscriberIdentity $subscriber
     *     @type int $status
     * }
     */
    public function __construct($data = NULL) {
        \Phluxor\Cluster\Metadata\ProtoBuf\Pubsub::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.cluster.SubscriberIdentity subscriber = 1;</code>
     * @return \Phluxor\Cluster\ProtoBuf\SubscriberIdentity|null
     */
    public function getSubscriber()
    {
        return $this->subscriber;
    }

    public function hasSubscriber()
    {
        return isset($this->subscriber);
    }

    public function clearSubscriber()
    {
        unset($this->subscriber);
    }

    /**
     * Generated from protobuf field <code>.cluster.SubscriberIdentity subscriber = 1;</code>
     * @param \Phluxor\Cluster\ProtoBuf\SubscriberIdentity $var
     * @return $this
     */
    public function setSubscriber($var)
    {
        GPBUtil::checkMessage($var, \Phluxor\Cluster\ProtoBuf\SubscriberIdentity::class);
        $this->subscriber = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.cluster.DeliveryStatus status = 2;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.cluster.DeliveryStatus status = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \Phluxor\Cluster\ProtoBuf\DeliveryStatus::class);
        $this->status = $var;

        return $this;
    }

}

