<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: actor.proto

namespace Phluxor\ActorSystem\ProtoBuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *user messages
 *
 * Generated from protobuf message <code>actor.PoisonPill</code>
 */
class PoisonPill extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \Phluxor\Metadata\ProtoBuf\Actor::initOnce();
        parent::__construct($data);
    }

}

