<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: actor.proto

namespace Phluxor\ActorSystem\ProtoBuf;

use UnexpectedValueException;

/**
 * Protobuf type <code>actor.TerminatedReason</code>
 */
class TerminatedReason
{
    /**
     * Generated from protobuf enum <code>Stopped = 0;</code>
     */
    const Stopped = 0;
    /**
     * Generated from protobuf enum <code>AddressTerminated = 1;</code>
     */
    const AddressTerminated = 1;
    /**
     * Generated from protobuf enum <code>NotFound = 2;</code>
     */
    const NotFound = 2;

    private static $valueToName = [
        self::Stopped => 'Stopped',
        self::AddressTerminated => 'AddressTerminated',
        self::NotFound => 'NotFound',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

