<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: actor.proto

namespace Phluxor\ActorSystem\ProtoBuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>actor.Touched</code>
 */
class Touched extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.actor.PID who = 1;</code>
     */
    protected $who = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Phluxor\ActorSystem\ProtoBuf\PID $who
     * }
     */
    public function __construct($data = NULL) {
        \Phluxor\Metadata\ProtoBuf\Actor::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.actor.PID who = 1;</code>
     * @return \Phluxor\ActorSystem\ProtoBuf\PID|null
     */
    public function getWho()
    {
        return $this->who;
    }

    public function hasWho()
    {
        return isset($this->who);
    }

    public function clearWho()
    {
        unset($this->who);
    }

    /**
     * Generated from protobuf field <code>.actor.PID who = 1;</code>
     * @param \Phluxor\ActorSystem\ProtoBuf\PID $var
     * @return $this
     */
    public function setWho($var)
    {
        GPBUtil::checkMessage($var, \Phluxor\ActorSystem\ProtoBuf\PID::class);
        $this->who = $var;

        return $this;
    }

}

