<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: router.proto

namespace Phluxor\Router\ProtoBuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>router.AddRoutee</code>
 */
class AddRoutee extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.actor.PID PID = 1;</code>
     */
    protected $PID = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Phluxor\ActorSystem\ProtoBuf\PID $PID
     * }
     */
    public function __construct($data = NULL) {
        \Phluxor\Router\Metadata\ProtoBuf\Router::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.actor.PID PID = 1;</code>
     * @return \Phluxor\ActorSystem\ProtoBuf\PID|null
     */
    public function getPID()
    {
        return $this->PID;
    }

    public function hasPID()
    {
        return isset($this->PID);
    }

    public function clearPID()
    {
        unset($this->PID);
    }

    /**
     * Generated from protobuf field <code>.actor.PID PID = 1;</code>
     * @param \Phluxor\ActorSystem\ProtoBuf\PID $var
     * @return $this
     */
    public function setPID($var)
    {
        GPBUtil::checkMessage($var, \Phluxor\ActorSystem\ProtoBuf\PID::class);
        $this->PID = $var;

        return $this;
    }

}

