<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: router.proto

namespace Phluxor\Router\ProtoBuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>router.Routees</code>
 */
class Routees extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .actor.Pid pids = 1;</code>
     */
    private $pids;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Phluxor\ActorSystem\ProtoBuf\Pid>|\Google\Protobuf\Internal\RepeatedField $pids
     * }
     */
    public function __construct($data = NULL) {
        \Phluxor\Router\Metadata\ProtoBuf\Router::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .actor.Pid pids = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPids()
    {
        return $this->pids;
    }

    /**
     * Generated from protobuf field <code>repeated .actor.Pid pids = 1;</code>
     * @param array<\Phluxor\ActorSystem\ProtoBuf\Pid>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPids($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Phluxor\ActorSystem\ProtoBuf\Pid::class);
        $this->pids = $arr;

        return $this;
    }

}

