<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cluster.proto

namespace Phluxor\Cluster\ProtoBuf\IdentityHandoverAck;

use UnexpectedValueException;

/**
 * Protobuf type <code>cluster.IdentityHandoverAck.State</code>
 */
class State
{
    /**
     * Generated from protobuf enum <code>processed = 0;</code>
     */
    const processed = 0;
    /**
     * Generated from protobuf enum <code>incorrect_topology = 1;</code>
     */
    const incorrect_topology = 1;

    private static $valueToName = [
        self::processed => 'processed',
        self::incorrect_topology => 'incorrect_topology',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

