name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        phps: [
          {version: '8.3', swoole: 'swoole-6.0.0'},
          #{version: '8.4', swoole: 'swoole-6.0.0'}
        ]
    name: PHP ${{ matrix.phps.version }} Test
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.phps.version }}
          extensions: ${{ matrix.phps.swoole }}
          coverage: none
      - name: Validate composer.json and composer.lock
        run: composer validate
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
      - name: build container
        run: docker compose -f ./tests/compose.yaml up -d
      - name: sqlite3
        run: sqlite3 ./tests/sqlite/data/data.db < ./tests/sqlite/create.sql
      - name: Execute tests
        run: ./vendor/bin/phpunit
