name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.3']
        swooles: ['swoole', 'openswoole']
    name: PHP ${{ matrix.php-versions }} Test
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ${{ matrix.swooles }}
          coverage: none
      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
      - name: Determine if swoole or openswoole
        if: matrix.swooles == 'openswoole'
        run: composer require openswoole/core
      - name: build container
        run: docker compose -f ./tests/compose.yaml up -d
      - name: Execute tests
        run: composer tests
